//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfTestClient.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExtentionData", Namespace="http://itstep.dp.ua/TestWCF")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WcfTestClient.ServiceReference1.ExtType))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WcfTestClient.ServiceReference1.ExtType2))]
    public partial class ExtentionData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OptionalDataField;
        
        private bool ImportantDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OptionalData {
            get {
                return this.OptionalDataField;
            }
            set {
                if ((object.ReferenceEquals(this.OptionalDataField, value) != true)) {
                    this.OptionalDataField = value;
                    this.RaisePropertyChanged("OptionalData");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public bool ImportantData {
            get {
                return this.ImportantDataField;
            }
            set {
                if ((this.ImportantDataField.Equals(value) != true)) {
                    this.ImportantDataField = value;
                    this.RaisePropertyChanged("ImportantData");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExtType", Namespace="http://schemas.datacontract.org/2004/07/WcfMsgLog")]
    [System.SerializableAttribute()]
    public partial class ExtType : WcfTestClient.ServiceReference1.ExtentionData {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExtType2", Namespace="http://schemas.datacontract.org/2004/07/WcfMsgLog")]
    [System.SerializableAttribute()]
    public partial class ExtType2 : WcfTestClient.ServiceReference1.ExtentionData {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetSimpleData", ReplyAction="http://tempuri.org/IService1/GetSimpleDataResponse")]
        string GetSimpleData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetSimpleData", ReplyAction="http://tempuri.org/IService1/GetSimpleDataResponse")]
        System.Threading.Tasks.Task<string> GetSimpleDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetExtData", ReplyAction="http://tempuri.org/IService1/GetExtDataResponse")]
        WcfTestClient.ServiceReference1.ExtentionData GetExtData(WcfTestClient.ServiceReference1.ExtentionData composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetExtData", ReplyAction="http://tempuri.org/IService1/GetExtDataResponse")]
        System.Threading.Tasks.Task<WcfTestClient.ServiceReference1.ExtentionData> GetExtDataAsync(WcfTestClient.ServiceReference1.ExtentionData composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAdditionalDAta", ReplyAction="http://tempuri.org/IService1/GetAdditionalDAtaResponse")]
        WcfTestClient.ServiceReference1.ExtType GetAdditionalDAta(WcfTestClient.ServiceReference1.ExtType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAdditionalDAta", ReplyAction="http://tempuri.org/IService1/GetAdditionalDAtaResponse")]
        System.Threading.Tasks.Task<WcfTestClient.ServiceReference1.ExtType> GetAdditionalDAtaAsync(WcfTestClient.ServiceReference1.ExtType composite);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : WcfTestClient.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<WcfTestClient.ServiceReference1.IService1>, WcfTestClient.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetSimpleData(int value) {
            return base.Channel.GetSimpleData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetSimpleDataAsync(int value) {
            return base.Channel.GetSimpleDataAsync(value);
        }
        
        public WcfTestClient.ServiceReference1.ExtentionData GetExtData(WcfTestClient.ServiceReference1.ExtentionData composite) {
            return base.Channel.GetExtData(composite);
        }
        
        public System.Threading.Tasks.Task<WcfTestClient.ServiceReference1.ExtentionData> GetExtDataAsync(WcfTestClient.ServiceReference1.ExtentionData composite) {
            return base.Channel.GetExtDataAsync(composite);
        }
        
        public WcfTestClient.ServiceReference1.ExtType GetAdditionalDAta(WcfTestClient.ServiceReference1.ExtType composite) {
            return base.Channel.GetAdditionalDAta(composite);
        }
        
        public System.Threading.Tasks.Task<WcfTestClient.ServiceReference1.ExtType> GetAdditionalDAtaAsync(WcfTestClient.ServiceReference1.ExtType composite) {
            return base.Channel.GetAdditionalDAtaAsync(composite);
        }
    }
}
